name: linting
on:
  pull_request:
    branches:
      - "main"
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dev dependencies
        run: npm install

      - name: Run Linting on Code Base
        uses: github/super-linter/slim@v4.9.4
        env:
          DEFAULT_BRANCH: main
          DEFAULT_WORKSPACE: .
          LINTER_RULES_PATH: ".github/linters"
          FILTER_REGEX_EXCLUDE: examples/|jest\.config\.ts
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: InvalidToken
